// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_home.h"
#include "screens/ui_setting.h"
#include "screens/ui_home1.h"
#include "screens/ui_brightness.h"
#include "screens/ui_systemInfo.h"
#include "screens/ui_weather.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bizhi_png);    // assets/bizhi.png
LV_IMG_DECLARE(ui_img_connect_wifi_png);    // assets/connect_wifi.png
LV_IMG_DECLARE(ui_img_sun_png);    // assets/sun.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_brightness_png);    // assets/brightness.png
LV_IMG_DECLARE(ui_img_systeminfo_png);    // assets/systemInfo.png
LV_IMG_DECLARE(ui_img_weather_png);    // assets/weather.png
LV_IMG_DECLARE(ui_img_cloudy_png);    // assets/cloudy.png
LV_IMG_DECLARE(ui_img_sprinkle_png);    // assets/sprinkle.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
