// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
typedef struct
{
    /* data */
    lv_obj_t *obj;
    uint8_t obj_num;
}obj_t;

extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label13;
void update_time_cb(lv_timer_t *timer);
void brightness_cb(lv_event_t *e);
void wifionOff_cb(lv_event_t* e);
void system_runtime_cb(lv_timer_t *timer);
void update_weather_cb(lv_timer_t *timer);
#ifdef __cplusplus
extern "C" }
#endif

#endif
