// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_BRIGHTNESS_H
#define UI_BRIGHTNESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_brightness
extern void ui_brightness_screen_init(void);
extern void ui_brightness_screen_destroy(void);
extern lv_obj_t * ui_brightness;
extern lv_obj_t * ui_Panel10;
extern void ui_event_Image8(lv_event_t * e);
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Panel11;
extern void ui_event_Image9(lv_event_t * e);
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Slider1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

