// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_brightness = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Slider1 = NULL;
// event funtions
void ui_event_Image8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_home_screen_init);
    }
}

void ui_event_Image9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_home1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_home1_screen_init);
    }
}

// build funtions

void ui_brightness_screen_init(void)
{
    ui_brightness = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_brightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_brightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_brightness, &ui_img_bizhi_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_brightness, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_image_opa(ui_brightness, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_brightness);
    lv_obj_set_width(ui_Panel10, 64);
    lv_obj_set_height(ui_Panel10, 64);
    lv_obj_set_x(ui_Panel10, 0);
    lv_obj_set_y(ui_Panel10, 210);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_image_create(ui_Panel10);
    lv_image_set_src(ui_Image8, &ui_img_home_png);
    lv_obj_set_size(ui_Image8, 64, 64);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Image8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_brightness);
    lv_obj_set_width(ui_Panel11, 64);
    lv_obj_set_height(ui_Panel11, 64);
    lv_obj_set_x(ui_Panel11, -103);
    lv_obj_set_y(ui_Panel11, 211);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_image_opa(ui_Panel11, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Panel11, lv_color_hex(0x4040FF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Panel11, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image9 = lv_image_create(ui_Panel11);
    lv_image_set_src(ui_Image9, &ui_img_back_png);
    lv_obj_set_size(ui_Image9, 64, 64);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image9, lv_color_hex(0xFAF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Image9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Image9, lv_color_hex(0x000007), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Image9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_brightness);
    lv_obj_set_width(ui_Panel12, 301);
    lv_obj_set_height(ui_Panel12, 50);
    lv_obj_set_x(ui_Panel12, 0);
    lv_obj_set_y(ui_Panel12, -171);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -95);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "brightness:");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Panel12);
    lv_slider_set_value(ui_Slider1, 50, LV_ANIM_OFF);
    lv_slider_set_range(ui_Slider1,0,100);
    lv_slider_set_mode(ui_Slider1,LV_SLIDER_MODE_NORMAL);
    // if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 20);
    lv_obj_set_x(ui_Slider1, 73);
    lv_obj_set_y(ui_Slider1, 2);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_Image8, ui_event_Image8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image9, ui_event_Image9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel10, ui_event_Image8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel11, ui_event_Image9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1,brightness_cb,LV_EVENT_VALUE_CHANGED,NULL);

}

void ui_brightness_screen_destroy(void)
{
    if(ui_brightness) lv_obj_del(ui_brightness);

    // NULL screen variables
    ui_brightness = NULL;
    ui_Panel10 = NULL;
    ui_Image8 = NULL;
    ui_Panel11 = NULL;
    ui_Image9 = NULL;
    ui_Panel12 = NULL;
    ui_Label6 = NULL;
    ui_Slider1 = NULL;

}
