// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_HOME1_H
#define UI_HOME1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home1
extern void ui_home1_screen_init(void);
extern void ui_home1_screen_destroy(void);
extern void ui_event_home1(lv_event_t * e);
extern lv_obj_t * ui_home1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel5;
extern void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

