// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_home1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Panel20 = NULL;
lv_obj_t * ui_Image12 = NULL;
static obj_t obj;
// event funtions
void ui_event_home1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_home_screen_init);
    }
}

void ui_event_Panel5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_setting_screen_init);
    }
}

void ui_event_Image4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_setting, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_setting_screen_init);
    }
}

void ui_event_Panel8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_brightness, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_brightness_screen_init);
    }
}

void ui_event_Image6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_brightness, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_brightness_screen_init);
    }
}

void ui_event_Panel9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_systemInfo, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_systemInfo_screen_init);
    }
}

void ui_event_Image7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_systemInfo, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_systemInfo_screen_init);
    }
}
void ui_event_Panel20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_weather, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_weather_screen_init);
    }
}

void ui_event_Image12(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_weather, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_weather_screen_init);
    }
}
// build funtions

void ui_home1_screen_init(void)
{
    ui_home1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_home1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_home1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_home1, &ui_img_bizhi_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_home1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_home1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_home1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_home1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_home1);
    lv_obj_set_width(ui_Panel1, 320);
    lv_obj_set_height(ui_Panel1, 20);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -277);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xD6D3D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_Panel1, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel1, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Panel1);
    lv_image_set_src(ui_Image1, &ui_img_connect_wifi_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 71);
    lv_obj_set_y(ui_Image1, -1);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_HIDDEN);

    ui_Label2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -134);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "15:37");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFBF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_home1);
    lv_obj_set_width(ui_Panel5, 100);
    lv_obj_set_height(ui_Panel5, 100);
    lv_obj_set_x(ui_Panel5, -75);
    lv_obj_set_y(ui_Panel5, -103);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_grad_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_Panel5);
    lv_image_set_src(ui_Image4, &ui_img_setting_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, 89);
    lv_obj_set_y(ui_Image4, -38);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_Image4, LV_IMAGE_ALIGN_TOP_LEFT);
    lv_obj_set_style_bg_grad_color(ui_Image4, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(ui_Image4, lv_color_hex(0x050000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_home1);
    lv_obj_set_width(ui_Panel8, 100);
    lv_obj_set_height(ui_Panel8, 100);
    lv_obj_set_x(ui_Panel8, 81);
    lv_obj_set_y(ui_Panel8, -100);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_image_create(ui_Panel8);
    lv_image_set_src(ui_Image6, &ui_img_brightness_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -1);
    lv_obj_set_y(ui_Image6, 3);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image6, 512);

    ui_Panel9 = lv_obj_create(ui_home1);
    lv_obj_set_width(ui_Panel9, 100);
    lv_obj_set_height(ui_Panel9, 100);
    lv_obj_set_x(ui_Panel9, -75);
    lv_obj_set_y(ui_Panel9, 41);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_image_create(ui_Panel9);
    lv_image_set_src(ui_Image7, &ui_img_systeminfo_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image7, 600);

    ui_Panel20 = lv_obj_create(ui_home1);
    lv_obj_set_width(ui_Panel20, 100);
    lv_obj_set_height(ui_Panel20, 100);
    lv_obj_set_x(ui_Panel20, 81);
    lv_obj_set_y(ui_Panel20, 41);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_image_create(ui_Panel20);
    lv_image_set_src(ui_Image12, &ui_img_weather_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image12, 512);

    lv_obj_add_event_cb(ui_Image4, ui_event_Image4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel5, ui_event_Panel5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image6, ui_event_Image6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel8, ui_event_Panel8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image7, ui_event_Image7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel9, ui_event_Panel9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image12, ui_event_Image12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel20, ui_event_Panel20, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_home1, ui_event_home1, LV_EVENT_ALL, NULL);

    obj.obj=ui_Label2;
    obj.obj_num = 0;
    lv_timer_create(update_time_cb, 1000, &obj);
}

void ui_home1_screen_destroy(void)
{
    if(ui_home1) lv_obj_del(ui_home1);

    // NULL screen variables
    ui_home1 = NULL;
    ui_Panel1 = NULL;
    ui_Image1 = NULL;
    ui_Label2 = NULL;
    ui_Panel5 = NULL;
    ui_Image4 = NULL;
    ui_Panel8 = NULL;
    ui_Image6 = NULL;
    ui_Panel9 = NULL;
    ui_Image7 = NULL;

}
