// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_setting
extern void ui_setting_screen_init(void);
extern void ui_setting_screen_destroy(void);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_Panel4;
extern void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel6;
extern void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Switch1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

