// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SYSTEMINFO_H
#define UI_SYSTEMINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_systemInfo
extern void ui_systemInfo_screen_init(void);
extern void ui_systemInfo_screen_destroy(void);
extern lv_obj_t * ui_systemInfo;
extern lv_obj_t * ui_Panel14;
extern void ui_event_Image10(lv_event_t * e);
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Panel15;
extern void ui_event_Image11(lv_event_t * e);
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

