// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_weather = NULL;
lv_obj_t * ui_Panel21 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Panel22 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_today = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_tomorrow = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_DayAfter = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Label17 = NULL;
// event funtions
void ui_event_Image13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_home_screen_init);
    }
}

void ui_event_Image14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_home1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_home1_screen_init);
    }
}

// build funtions

void ui_weather_screen_init(void)
{
    ui_weather = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_weather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_weather, &ui_img_bizhi_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_weather, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_image_opa(ui_weather, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_weather, 50, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_weather, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_weather);
    lv_obj_set_width(ui_Panel21, 64);
    lv_obj_set_height(ui_Panel21, 64);
    lv_obj_set_x(ui_Panel21, 0);
    lv_obj_set_y(ui_Panel21, 210);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_width(ui_Panel21, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_image_create(ui_Panel21);
    lv_image_set_src(ui_Image13, &ui_img_home_png);
    lv_obj_set_size(ui_Image13, 64, 64);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Image13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel22 = lv_obj_create(ui_weather);
    lv_obj_set_width(ui_Panel22, 64);
    lv_obj_set_height(ui_Panel22, 64);
    lv_obj_set_x(ui_Panel22, -103);
    lv_obj_set_y(ui_Panel22, 211);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_bg_image_opa(ui_Panel22, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Panel22, lv_color_hex(0x4040FF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Panel22, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image14 = lv_image_create(ui_Panel22);
    lv_image_set_src(ui_Image14, &ui_img_back_png);
    lv_obj_set_size(ui_Image14, 64, 64);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Image14, lv_color_hex(0xFAF7F7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Image14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Image14, lv_color_hex(0x000007), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Image14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabView1 = lv_tabview_create(ui_weather);
    lv_tabview_set_tab_bar_size(ui_TabView1, 40);
    lv_obj_set_width(ui_TabView1, 271);
    lv_obj_set_height(ui_TabView1, 200);
    lv_obj_set_x(ui_TabView1, 2);
    lv_obj_set_y(ui_TabView1, -16);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TabView1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TabView1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_TabView1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_today = lv_tabview_add_tab(ui_TabView1, "2025/8/5");
    lv_obj_set_flex_flow(ui_today, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_today, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    lv_obj_set_style_border_width(ui_today, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_today, 50, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_today, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Image15 = lv_image_create(ui_today);
    lv_image_set_src(ui_Image15, &ui_img_sun_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, -119);
    lv_obj_set_y(ui_Image15, 43);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_Image15, 20, 0);
    lv_image_set_scale(ui_Image15, 815);
    lv_obj_set_style_image_recolor(ui_Image15, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_Image15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_today);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 63);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "sun");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label15, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tomorrow = lv_tabview_add_tab(ui_TabView1, "2025/8/6");
    lv_obj_set_flex_flow(ui_tomorrow, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_tomorrow, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Image16 = lv_image_create(ui_tomorrow);
    lv_image_set_src(ui_Image16, &ui_img_cloudy_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_Image16, 20, 0);
    lv_image_set_scale(ui_Image16, 815);

    ui_Label16 = lv_label_create(ui_tomorrow);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "cloudy");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label16, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DayAfter = lv_tabview_add_tab(ui_TabView1, "2025/8/7");
    lv_obj_set_flex_flow(ui_DayAfter, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DayAfter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Image17 = lv_image_create(ui_DayAfter);
    lv_image_set_src(ui_Image17, &ui_img_sprinkle_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_Image17, 20, 0);
    lv_image_set_scale(ui_Image17, 815);

    ui_Label17 = lv_label_create(ui_DayAfter);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "rainy");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label17, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label17, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image13, ui_event_Image13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image14, ui_event_Image14, LV_EVENT_ALL, NULL);

}

void ui_weather_screen_destroy(void)
{
    if(ui_weather) lv_obj_del(ui_weather);

    // NULL screen variables
    ui_weather = NULL;
    ui_Panel21 = NULL;
    ui_Image13 = NULL;
    ui_Panel22 = NULL;
    ui_Image14 = NULL;
    ui_TabView1 = NULL;
    ui_today = NULL;
    ui_Image15 = NULL;
    ui_Label15 = NULL;
    ui_tomorrow = NULL;
    ui_Image16 = NULL;
    ui_Label16 = NULL;
    ui_DayAfter = NULL;
    ui_Image17 = NULL;
    ui_Label17 = NULL;

}
