// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_WEATHER_H
#define UI_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_weather
extern void ui_weather_screen_init(void);
extern void ui_weather_screen_destroy(void);
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_Panel21;
extern void ui_event_Image13(lv_event_t * e);
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Panel22;
extern void ui_event_Image14(lv_event_t * e);
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_today;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_tomorrow;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_DayAfter;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label17;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

